//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dll.rc
//
#define IDI_ICON1                       102
#define IDD_DIALOG1                     103
#define IDD_DIALOGENG                   103
#define IDD_DIALOGHUN                   104
#define IDC_GLIDEINFO                   1000
#define IDS_BASE                        10000
#define IDS_INITERRORTITLE              10000
#define IDS_NODIRECTXINSTALLED          10001
#define IDS_CANNOTRUNASSERVER           10002
#define IDS_SERVERISALREADYRUNNING      10003
#define IDS_CANNOTCREATEMEMORYMAPPING   10004
#define IDS_CANNOTCREATEWIN32OBJECTS    10005
#define IDS_INCOMPATIBLEDESKTOPMODE     10006
#define IDS_CANNOTLOADVXD               10007
#define IDS_VESAINITFAILED              10008
#define IDS_SERVERKILLERRORTITLE        10009
#define IDS_SURETOKILLSERVER            10010
#define IDS_LFBSAVEDTOCLIPBOARD         10011
#define IDS_LFBSAVEDTOFILEPREFIX        10012
#define IDS_LFBSAVEDTOFILESUFFIX        10013
#define IDS_LFBSAVINGTOFILEFAILED       10014
#define IDS_OPENSERVERTITLE             10015
#define IDS_OPENSERVERFAILED            10016
#define IDS_BASE_HUN                    11000
#define IDS_INITERRORTITLE_HUN          11000
#define IDS_NODIRECTXINSTALLED_HUN      11001
#define IDS_CANNOTRUNASSERVER_HUN       11002
#define IDS_SERVERISALREADYRUNNING_HUN  11003
#define IDS_CANNOTCREATEMEMORYMAPPING_HUN 11004
#define IDS_CANNOTCREATEWIN32OBJECTS_HUN 11005
#define IDS_INCOMPATIBLEDESKTOPMODE_HUN 11006
#define IDS_CANNOTLOADVXD_HUN           11007
#define IDS_VESAINITFAILED_HUN          11008
#define IDS_SERVERKILLERRORTITLE_HUN    11009
#define IDS_SURETOKILLSERVER_HUN        11010
#define IDS_LFBSAVEDTOCLIPBOARD_HUN     11011
#define IDS_STRING11012                 11012
#define IDS_LFBSAVEDTOFILEPREFIX_HUN    11012
#define IDS_LFBSAVEDTOFILESUFFIX_HUN    11013
#define IDS_LFBSAVINGTOFILEFAILED_HUN   11014
#define IDS_OPENSERVERTITLE_HUN         11015
#define IDS_OPENSERVERFAILED_HUN        11016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
