//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dgVoodooSetupLoc.rc
//
#define IDS_LANGNAME                    1
#define IDD_DIALOG1                     100
#define IDD_DIALOG2                     101
#define IDD_DIALOGABOUT                 101
#define IDI_ICON1                       104
#define IDB_BITMAP1                     105
#define IDD_DIALOGGLIDE                 114
#define IDD_DIALOGGLOBAL                115
#define IDD_DIALOGVESA                  116
#define IDD_DIALOGMAIN                  117
#define IDD_DIALOGTOP                   122
#define IDR_FLOATINGMENU                124
#define IDD_DIALOGBOTTOM                124
#define IDB_BITMAP2                     145
#define IDR_FORMATSTRENG                149
#define IDR_FORMATSTRHUN                150
#define IDD_CMDLINEHELP                 151
#define IDR_CMDLINEHELP                 152
#define IDD_DIALOGRENDERER              152
#define IDC_SBDBOX                      200
#define IDC_SCRMODE                     201
#define IDC_DXBITDEPTH                  202
#define IDC_CURRSET                     203
#define IDC_REFRATE                     204
#define IDC_STATIC1                     205
#define IDC_DEPTHBUFF                   206
#define IDC_LFBACC                      207
#define IDC_NOLFBACC                    208
#define IDC_ENWBUFF                     209
#define IDC_EMWBUFF                     210
#define IDC_DISWBUFF                    211
#define IDC_DEPTHBUFF2                  211
#define IDC_RADIO4                      212
#define IDC_TEX32                       213
#define IDC_RRMONITOR                   214
#define IDC_RRAPP                       215
#define IDC_16BIT                       216
#define IDC_32BIT                       217
#define IDC_FULLSCR                     218
#define IDC_WINDOWED                    219
#define IDC_OKBUTTON                    221
#define IDC_TEXMEM                      222
#define IDC_COMBOTEXMEMSIZE             223
#define IDC_COMBOTEXNUM                 224
#define IDC_COMBOLFBACCESS              224
#define IDC_STATIC4                     225
#define IDC_STATIC2                     226
#define IDC_DESKTOPTEXT                 227
#define IDC_UNCOMPMODE                  228
#define IDC_SEARCH                      229
#define IDC_ACTDIR                      230
#define IDC_DGVINSTANCE                 231
#define IDC_ERROR                       232
#define IDC_CANCELBUTTON                233
#define IDC_WINDIR                      233
#define IDC_ABOUTBUTTON                 234
#define IDC_PWINDOWS                    235
#define IDC_PDOS                        236
#define IDC_SLIDER1                     237
#define IDC_SLIDERSTATIC                238
#define IDC_STATPERC1                   239
#define IDC_STATPERC3                   240
#define IDC_STATPERC2                   241
#define IDC_STATIC3                     242
#define ID_OK                           243
#define IDC_TEXOPT                      299
#define IDC_VESAENABLE                  1000
#define IDC_SLIDER2                     1001
#define IDC_COMBOVIDMEMSIZE             1002
#define IDC_HIDECONSOLE                 1003
#define IDC_SLIDERSTATIC2               1004
#define IDC_GAMMACORRECTION             1005
#define IDC_MISC                        1007
#define IDC_45HZ                        1009
#define IDC_70HZ                        1010
#define IDC_VESALABEL2                  1012
#define IDC_SETMOUSEFOCUS               1014
#define IDC_SUPPORTMODE13H              1015
#define IDC_DISABLEFLATLFB              1017
#define IDC_MAINTAB                     1025
#define IDC_COMBORESOLUTION             1026
#define IDC_GBVESAREFFREQ               1027
#define IDC_GBVESAVIDMEM                1028
#define IDC_GBVESAMISC                  1029
#define IDC_TEX16                       1031
#define IDC_TRIPLEBUFFER                1032
#define IDC_CHECK1                      1032
#define IDC_GLIDEMISC                   1037
#define IDC_TEXRELOAD                   1038
#define IDC_SCAPTUREON                  1039
#define IDC_SAVETOFILE                  1040
#define IDC_MIPMAPPINGDISABLE           1041
#define IDC_SAVETOCLIPBOARD             1042
#define IDC_CMTNT                       1043
#define IDC_CMGEFORCE                   1044
#define IDC_LANGENGLISH                 1045
#define IDC_LANGHUNGARIAN               1046
#define IDC_TOMBRAIDER                  1047
#define IDC_DISPDEV                     1048
#define IDC_CBDISPDEVS                  1049
#define IDC_RENDERER                    1050
#define IDC_DISPDRIVER                  1051
#define IDC_CBDISPDRIVERS               1052
#define IDC_RAPIBOX                     1053
#define IDC_HWBUFFCACHING               1054
#define IDC_REALHW                      1055
#define IDC_ACTIVEBACKG                 1057
#define IDC_VDDMODE                     1058
#define IDC_CLIPOPF                     1059
#define IDC_FASTWRITE                   1060
#define IDC_CTRLALT                     1061
#define IDC_PRESERVEWINDOWSIZE          1062
#define IDC_PRESERVEASPECTRATIO         1063
#define IDC_VSYNC                       1064
#define IDC_P8                          1065
#define IDC_PERFECTTEXEMU               1066
#define IDC_GAMMARAMP                   1067
#define IDC_FORCEWBUFFERING             1068
#define IDC_CLIPPING                    1070
#define IDC_HWVBUFFER                   1071
#define IDC_BILINEARFILTERING           1072
#define IDC_ALPHACK                     1073
#define IDC_TIMERLOOP                   1073
#define IDC_WINXPDOS                    1074
#define IDC_AUTOGENMIPMAPS              1074
#define IDC_TEXMEMSCALE                 1075
#define IDC_REFRESHRATEVALUE            1077
#define IDC_CLOSESTFREQ                 1078
#define IDC_REFRATESTATIC               1079
#define IDC_RESCALECHANGES              1081
#define IDC_TRILINEARMIPMAPS            1082
#define IDC_INSTANCELIST                1083
#define IDC_COMBOCOLORKEY               1084
#define IDC_COLORKEYSTATIC              1085
#define IDC_LFBTEXTURETILES             1086
#define IDC_CBLANGUAGE                  1086
#define IDC_HELPEDIT                    1087
#define IDC_BUTTON1                     1089
#define IDC_HELPOKBUTTON                1089
#define IDC_DX9FORCELFCOPY              1091
#define IDC_DX9FORCELFCOPY2             1092
#define IDC_DX9FORCEFFSHADERS           1093
#define IDC_DX9GRAYSCALERENDERING       1094
#define IDC_DX9NORETRACE                1095
#define IDC_RENDERERAPISTATUS           1096
#define IDC_DX9_HWPALETTEGEN            1097
#define IDC_SYSDIR                      1098
#define IDC_TEX32_HUN                   2213
#define IDC_16BIT_HUN                   2216
#define IDC_32BIT_HUN                   2217
#define IDC_FULLSCR_HUN                 2218
#define IDC_WINDOWED_HUN                2219
#define IDC_COMBOTEXMEMSIZE_HUN         2223
#define IDC_COMBOLFBACCESS_HUN          2224
#define IDC_SEARCH_HUN                  2229
#define IDC_ACTDIR_HUN                  2230
#define IDC_WINDIR_HUN                  2233
#define IDC_PWINDOWS_HUN                2235
#define IDC_PDOS_HUN                    2236
#define IDC_SLIDER1_HUN                 2237
#define IDC_TEXOPT_HUN                  2299
#define IDC_VESAENABLE_HUN              3000
#define IDC_SLIDER2_HUN                 3001
#define IDC_HIDECONSOLE_HUN             3003
#define IDC_SETMOUSEFOCUS_HUN           3014
#define IDC_SUPPORTMODE13H_HUN          3015
#define IDC_DISABLEFLATLFB_HUN          3017
#define IDC_COMBORESOLUTION_HUN         3026
#define IDC_TEX16_HUN                   3031
#define IDC_CHECK1_HUN                  3032
#define IDC_SAVETOFILE_HUN              3040
#define IDC_MIPMAPPINGDISABLE_HUN       3041
#define IDC_SAVETOCLIPBOARD_HUN         3042
#define IDC_LANGENGLISH_HUN             3045
#define IDC_LANGHUNGARIAN_HUN           3046
#define IDC_TOMBRAIDER_HUN              3047
#define IDC_CBDISPDEVS_HUN              3049
#define IDC_CBDISPDRIVERS_HUN           3052
#define IDC_HWBUFFCACHING_HUN           3054
#define IDC_REALHW_HUN                  3055
#define IDC_ACTIVEBACKG_HUN             3057
#define IDC_VDDMODE_HUN                 3058
#define IDC_FASTWRITE_HUN               3060
#define IDC_CTRLALT_HUN                 3061
#define IDC_PRESERVEWINDOWSIZE_HUN      3062
#define IDC_PRESERVEASPECTRATIO_HUN     3063
#define IDC_VSYNC_HUN                   3064
#define IDC_GAMMARAMP_HUN               3067
#define IDC_FORCEWBUFFERING_HUN         3068
#define IDC_HWVBUFFER_HUN               3071
#define IDC_BILINEARFILTERING_HUN       3072
#define IDC_TIMERLOOP_HUN               3073
#define IDC_AUTOGENMIPMAPS_HUN          3074
#define IDC_TEXMEMSCALE_HUN             3075
#define IDC_REFRESHRATEVALUE_HUN        3077
#define IDC_CLOSESTFREQ_HUN             3078
#define IDC_TRILINEARMIPMAPS_HUN        3082
#define IDC_COMBOCOLORKEY_HUN           3084
#define IDC_LFBTEXTURETILES_HUN         3086
#define IDC_DX9FORCELFCOPY_HUN          3091
#define IDC_DX9FORCEFFSHADERS_HUN       3093
#define IDC_DX9GRAYSCALERENDERING_HUN   3094
#define IDC_DX9NORETRACE_HUN            3095
#define IDC_DX9_HWPALETTEGEN_HUN        3097
#define IDC_SYSDIR_HUN                  3098
#define IDS_ENABLELFBACCESS             10000
#define IDS_LFBDISABLEREAD              10001
#define IDS_DISABLELFBWRITE             10002
#define IDS_DISABLELFBACCESS            10003
#define IDS_CKAUTOMATIC                 10004
#define IDS_CKALPHABASED                10005
#define IDS_CKNATIVE                    10006
#define IDS_NATIVEFORTNT                10007
#define IDS_REFRESHDEFAULT              10008
#define IDS_RESDEFAULT                  10009
#define IDS_DDRIVERDEFAULT              10010
#define IDS_DDEVICEUNKNOWN              10011
#define IDS_NOWRAPPERINSTANCE           10012
#define IDS_DESKTOPVIDEOMODE            10013
#define IDS_DESKTOPVIDEOMODEUNKNOWN     10014
#define IDS_INCOMPATIBELWRAPPERFILE     10015
#define IDS_INVALIDWRAPPERFILE          10016
#define IDS_NOWRAPPERFILEFOUND          10017
#define IDS_TABPANESTR1                 10018
#define IDS_CLASSISTABPANESTR1          10018
#define IDS_CLASSICTABPANESTR1          10018
#define IDS_TABPANESTR2                 10019
#define IDS_CLASSICTABPANESTR2          10019
#define IDS_TABPANESTR3                 10020
#define IDS_CLASSICTABPANESTR3          10020
#define IDS_CANNOTEXPORTCONFIG          10021
#define IDS_ERROR                       10022
#define IDS_CANNOTSAVECONFIG            10023
#define IDS_SEARCHINGINSTANCE           10024
#define IDS_NAMEOFTEXTFILE              10025
#define IDS_NAMEOFCONFIGFILE            10026
#define IDS_CANNOTLOADCONFIG            10027
#define IDS_INVALIDCONFIGFILE           10028
#define IDS_ERRORDURINGCONFIGREAD       10029
#define IDS_INVALIDWRAPPERFILE2         10030
#define IDS_ERRORDURINGSAVE             10031
#define IDS_CANNOTWRITECONFIG           10032
#define IDS_ALLFILES                    10033
#define IDS_DLLFILES                    10034
#define IDS_CONFIGFILES                 10035
#define IDS_CEINVALIDCFGERROR           10036
#define IDS_CEDOS                       10037
#define IDS_CEWINDOWS                   10038
#define IDS_CEENABLED                   10039
#define IDS_CEDISABLED                  10040
#define IDS_CEFULLSCR                   10041
#define IDS_CEWINDOWED                  10042
#define IDS_CE16BIT                     10043
#define IDS_CE32BIT                     10044
#define IDS_CEOPTIMAL                   10045
#define IDS_CEDETBYDESKTOP              10046
#define IDS_CESHOTTOCLIPBOARD           10047
#define IDS_CESHOTTOFILE                10048
#define IDS_CEWBUFFDRAWINGTEST          10049
#define IDS_CEWBUFFRELYONDRIVER         10050
#define IDS_CEWBUFFFORCEEMULATED        10051
#define IDS_CEWBUFFFORCEW               10052
#define IDS_CEREFRATEMONITOR            10053
#define IDS_TABPANESTR4                 10053
#define IDS_CLASSICTABPANESTR4          10053
#define IDS_REFRATEAPP                  10054
#define IDS_INCOMPATIBLEEXTVERSION      10055
#define IDS_LFBTEXAUTOMATIC             10056
#define IDS_LFBTEXDISABLED              10057
#define IDS_LFBTEXFORCED                10058
#define IDS_RENDERERAPINOTAVAILABLE     10059
#define IDS_CLASSICVIEWMENUSTR1         10060
#define IDS_TEXTFILESFILTER             10061
#define IDS_CONFIGFILESFILTER           10062
#define IDS_ALLFILESFILTER              10063
#define IDS_ENABLELFBACCESS_HUN         11000
#define IDS_LFBDISABLEREAD_HUN          11001
#define IDS_DISABLELFBWRITE_HUN         11002
#define IDS_DISABLELFBACCESS_HUN        11003
#define IDS_CKAUTOMATIC_HUN             11004
#define IDS_CKALPHABASED_HUN            11005
#define IDS_CKNATIVE_HUN                11006
#define IDS_NATIVEFORTNT_HUN            11007
#define IDS_REFRESHDEFAULT_HUN          11008
#define IDS_RESDEFAULT_HUN              11009
#define IDS_DDRIVERDEFAULT_HUN          11010
#define IDS_DDEVICEUNKNOWN_HUN          11011
#define IDS_NOWRAPPERINSTANCE_HUN       11012
#define IDS_DESKTOPVIDEOMODE_HUN        11013
#define IDS_DESKTOPVIDEOMODEUNKNOWN_HUN 11014
#define IDS_INCOMPATIBELWRAPPERFILE_HUN 11015
#define IDS_INVALIDWRAPPERFILE_HUN      11016
#define IDS_NOWRAPPERFILEFOUND_HUN      11017
#define IDS_TABPANESTR1_HUN             11018
#define IDS_TABPANESTR2_HUN             11019
#define IDS_TABPANESTR3_HUN             11020
#define IDS_CANNOTEXPORTCONFIG_HUN      11021
#define IDS_ERROR_HUN                   11022
#define IDS_CANNOTSAVECONFIG_HUN        11023
#define IDS_SEARCHINGINSTANCE_HUN       11024
#define IDS_NAMEOFTEXTFILE_HUN          11025
#define IDS_NAMEOFCONFIGFILE_HUN        11026
#define IDS_CANNOTLOADCONFIG_HUN        11027
#define IDS_INVALIDCONFIGFILE_HUN       11028
#define IDS_ERRORDURINGCONFIGREAD_HUN   11029
#define IDS_INVALIDWRAPPERFILE2_HUN     11030
#define IDS_ERRORDURINGSAVE_HUN         11031
#define IDS_CANNOTWRITECONFIG_HUN       11032
#define IDS_ALLFILES_HUN                11033
#define IDS_DLLFILES_HUN                11034
#define IDS_CONFIGFILES_HUN             11035
#define IDS_CEINVALIDCFGERROR_HUN       11036
#define IDS_CEDOS_HUN                   11037
#define IDS_CEWINDOWS_HUN               11038
#define IDS_CEENABLED_HUN               11039
#define IDS_CEDISABLED_HUN              11040
#define IDS_CEFULLSCR_HUN               11041
#define IDS_CEWINDOWED_HUN              11042
#define IDS_CE16BIT_HUN                 11043
#define IDS_CE32BIT_HUN                 11044
#define IDS_CEOPTIMAL_HUN               11045
#define IDS_CEDETBYDESKTOP_HUN          11046
#define IDS_CESHOTTOCLIPBOARD_HUN       11047
#define IDS_CESHOTTOFILE_HUN            11048
#define IDS_CEWBUFFDRAWINGTEST_HUN      11049
#define IDS_CEWBUFFRELYONDRIVER_HUN     11050
#define IDS_CEWBUFFFORCEEMULATED_HUN    11051
#define IDS_CEWBUFFFORCEW_HUN           11052
#define IDS_CEREFRATEMONITOR_HUN        11053
#define IDS_TABPANESTR4_HUN             11053
#define IDS_REFRATEAPP_HUN              11054
#define IDS_INCOMPATIBLEEXTVERSION_HUN  11055
#define IDS_LFBTEXAUTOMATIC_HUN         11056
#define IDS_LFBTEXDISABLED_HUN          11057
#define IDS_LFBTEXFORCED_HUN            11058
#define IDS_RENDERERAPINOTAVAILABLE_HUN 11059
#define IDM_EXPORTSETTINGS              40004
#define IDM_SAVECONFIG                  40005
#define IDM_LOADCONFIG                  40006
#define IDM_XPSTYLE                     40007
#define IDM_RENDERERSPECIFIC            40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
